name = "vavlo-worker"
main = "worker.js"
compatibility_date = "2024-11-01"

[vars]
ROOT = "/ImageAnnotationTool"
TTL_DAYS = "90"

[triggers]
crons = ["17 7 * * *"]  # daily cleanup

# Optional: add a route if you want a custom domain
# [routes]
# pattern = "api.vavlo.io/*"
# zone_name = "vavlo.io"
